### ISSUE TITLE
References need to be upgraded due to SA's

### ISSUE THREAD

**Issue by dlidstrom** [NLog/NLog.MailKit#221]
The latest published version, 5.2.0, _seems_ to be implicitly referencing packages with security advisories:

- Package 'MimeKit' 3.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-gmc6-fwg3-75m5
- Package 'System.Formats.Asn1' 6.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-447r-wph3-92pm
- Package 'System.Security.Cryptography.Pkcs' 6.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-555c-2p6r-68mm

**Comment by 304NotModified** [comment]
What are the minimum versions without security advisors?

**Comment by snakefoot** [comment]
@304NotModified Seems NLog.MailKit uses Azure DevOps instead of AppVeyor, so nuget-package-key has expired, and no idea how to update it (Prefer AppVeyor). Maybe you can help fix it?

**Comment by 304NotModified** [comment]
You could change it here:

https://dev.azure.com/NLogLogging/NLog/_settings/adminservices?resourceId=34a75039-ea88-4be8-84f3-0619845dbb68

**Comment by 304NotModified** [comment]
I've updated the api key

**Comment by 304NotModified** [comment]
@snakefoot because of the major dependency bump, maybe change the minor version number? So 5.3?

**Comment by snakefoot** [comment]
Sounds good



Sent from my Galaxy



-------- Original message --------
From: Julian Verdurmen ***@***.***>
Date: 16/11/2024 19:42 (GMT+01:00)
To: "NLog/NLog.MailKit" ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Mention ***@***.***>
Subject: Re: [NLog/NLog.MailKit] References need to be upgraded due to SA's (Issue #221)


@snakefoot<https://github.com/snakefoot> because of the major dependency bump, maybe change the minor version number? So 5.3?

**Comment by 304NotModified** [comment]
Fixed in 5.3!

**Comment by snakefoot** [comment]
Thank you, much appreciated.
